apiVersion: v1
kind: ConfigMap
metadata:
  name: hrms-config
  labels: { app.kubernetes.io/part-of: hrms }
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.environment | default "prod" | quote }}
  ENVIRONMENT: {{ .Values.global.environment | default "prod" | quote }}
  IMAGE_TAG: {{ .Values.global.imageTag | quote }}
  REGION: {{ .Values.global.region | default "us-east-1" | quote }}
  TZ: {{ .Values.global.timezone | default "Asia/Kolkata" | quote }}
  EUREKA_URI: {{ .Values.env.EUREKA_SERVER_URL | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}
  REDIS_HOST: {{ .Values.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
  DB_HOST: {{ .Values.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  ELASTICSEARCH_URI: {{ .Values.env.ELASTICSEARCH_URI | quote }}
  STORAGE_ENDPOINT: {{ .Values.env.STORAGE_ENDPOINT | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
  TRACING_SAMPLE_RATE: {{ .Values.global.tracingSampleRate | default "0.1" | quote }}
