server:
  port: ${PORT:8111}
spring:
  application:
    name: service-cases
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:hrms_db}
    username: ${DB_USER:hrms_user}
    password: ${DB_PASSWORD:hrms_pass}
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history_cases
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer.group-id: service-cases
eureka:
  client.service-url.defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
