CREATE TABLE visitors (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id                VARCHAR(100) NOT NULL,
    full_name                VARCHAR(200) NOT NULL,
    company                  VARCHAR(200),
    email                    VARCHAR(200),
    phone                    VARCHAR(30),
    purpose                  VARCHAR(500),
    host_employee_id         UUID,
    location_id              UUID,
    arrival_at               TIMESTAMPTZ,
    expected_departure_at    TIMESTAMPTZ,
    actual_departure_at      TIMESTAMPTZ,
    badge_number             VARCHAR(50),
    photo_uri                VARCHAR(1000),
    id_proof_type            VARCHAR(30),
    id_proof_number_masked   VARCHAR(250),
    nda_signed               BOOLEAN,
    vehicle_number           VARCHAR(20),
    status                   VARCHAR(20) NOT NULL,
    created_by               VARCHAR(100),
    updated_by               VARCHAR(100),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted                  BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_visitor_date ON visitors (tenant_id, arrival_at);

CREATE TABLE meeting_rooms (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id                VARCHAR(100) NOT NULL,
    name                     VARCHAR(200) NOT NULL,
    code                     VARCHAR(50) NOT NULL,
    location_id              UUID NOT NULL,
    floor                    VARCHAR(50),
    capacity                 INTEGER NOT NULL,
    amenities                JSONB,
    is_bookable              BOOLEAN,
    requires_approval        BOOLEAN,
    approver_employee_id     UUID,
    photo_uri                VARCHAR(1000),
    is_active                BOOLEAN NOT NULL DEFAULT TRUE,
    created_by               VARCHAR(100),
    updated_by               VARCHAR(100),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted                  BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE room_bookings (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id                   VARCHAR(100) NOT NULL,
    room_id                     UUID NOT NULL REFERENCES meeting_rooms(id) ON DELETE CASCADE,
    organizer_employee_id       UUID NOT NULL,
    title                       VARCHAR(200) NOT NULL,
    description                 VARCHAR(2000),
    starts_at                   TIMESTAMPTZ NOT NULL,
    ends_at                     TIMESTAMPTZ NOT NULL,
    expected_attendee_count     INTEGER,
    attendee_employee_ids       JSONB,
    external_attendee_emails    JSONB,
    is_recurring                BOOLEAN,
    recurrence_rule             VARCHAR(500),
    status                      VARCHAR(20) NOT NULL,
    cancellation_reason         VARCHAR(500),
    created_by                  VARCHAR(100),
    updated_by                  VARCHAR(100),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted                     BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_booking_room_time ON room_bookings (room_id, starts_at);
CREATE INDEX ix_booking_organizer ON room_bookings (tenant_id, organizer_employee_id);

CREATE TABLE cab_bookings (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id                VARCHAR(100) NOT NULL,
    employee_id              UUID NOT NULL,
    booking_type             VARCHAR(30) NOT NULL,
    pickup_at                TIMESTAMPTZ NOT NULL,
    pickup_address           VARCHAR(500),
    drop_address             VARCHAR(500),
    drop_latitude            DOUBLE PRECISION,
    drop_longitude           DOUBLE PRECISION,
    estimated_distance_km    DOUBLE PRECISION,
    estimated_cost           NUMERIC(10,2),
    currency                 VARCHAR(3),
    vendor_name              VARCHAR(100),
    vendor_booking_id        VARCHAR(100),
    driver_name              VARCHAR(100),
    driver_phone             VARCHAR(30),
    vehicle_number           VARCHAR(20),
    reason                   VARCHAR(500),
    is_after_hours           BOOLEAN,
    needs_security_escort    BOOLEAN,
    actual_pickup_at         TIMESTAMPTZ,
    actual_drop_at           TIMESTAMPTZ,
    actual_cost              NUMERIC(10,2),
    trip_rating              INTEGER,
    trip_feedback            VARCHAR(2000),
    status                   VARCHAR(20) NOT NULL,
    created_by               VARCHAR(100),
    updated_by               VARCHAR(100),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted                  BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_cab_emp_date ON cab_bookings (tenant_id, employee_id, pickup_at);
