CREATE TABLE IF NOT EXISTS workflow_templates (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     VARCHAR(100),
    code          VARCHAR(100) NOT NULL UNIQUE,
    name          VARCHAR(200) NOT NULL,
    description   VARCHAR(1000),
    category      VARCHAR(100),
    icon          VARCHAR(50),
    steps         JSONB NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted       BOOLEAN NOT NULL DEFAULT FALSE
);

-- Seed library of common HR workflows. Tenants clone these into their own workflows.
INSERT INTO workflow_templates (code, name, description, category, icon, steps) VALUES
('LEAVE_MGR',          'Leave Approval - Manager only',
 'Single-step manager approval for routine leave requests',  'LEAVE',  'calendar',
 '[{"stepOrder":1,"stepName":"Manager Approval","stepType":"APPROVAL","approverType":"MANAGER","slaHours":24,"required":true}]'),
('LEAVE_MGR_HR',       'Leave Approval - Manager + HR',
 'Two-step: manager then HR — used for long leaves',         'LEAVE',  'calendar',
 '[{"stepOrder":1,"stepName":"Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":24,"required":true},
   {"stepOrder":2,"stepName":"HR","stepType":"APPROVAL","approverType":"HR","slaHours":48,"required":true}]'),
('EXPENSE_LT_10K',     'Expense - Below ₹10,000 - Manager only',
 'Auto-approved if amount is under 10k',                     'EXPENSE','wallet',
 '[{"stepOrder":1,"stepName":"Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":48,"required":true}]'),
('EXPENSE_GT_10K',     'Expense - Above ₹10,000 - Manager + Finance',
 'Two-step approval over 10k',                               'EXPENSE','wallet',
 '[{"stepOrder":1,"stepName":"Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":48,"required":true},
   {"stepOrder":2,"stepName":"Finance","stepType":"APPROVAL","approverType":"ROLE","approverRole":"FINANCE","slaHours":72,"required":true}]'),
('TRAVEL_MGR_FIN_HR',  'Travel - Manager + Finance + HR',
 'Three-step for domestic / international travel',           'TRAVEL', 'plane',
 '[{"stepOrder":1,"stepName":"Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":48,"required":true},
   {"stepOrder":2,"stepName":"Finance","stepType":"APPROVAL","approverType":"ROLE","approverRole":"FINANCE","slaHours":72,"required":true},
   {"stepOrder":3,"stepName":"HR","stepType":"APPROVAL","approverType":"HR","slaHours":48,"required":false}]'),
('HIRING_REQ',         'Hiring Requisition',
 'Standard requisition flow: hiring manager → HR → finance', 'HIRING', 'briefcase',
 '[{"stepOrder":1,"stepName":"Hiring Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":48,"required":true},
   {"stepOrder":2,"stepName":"HR","stepType":"APPROVAL","approverType":"HR","slaHours":72,"required":true},
   {"stepOrder":3,"stepName":"Finance","stepType":"APPROVAL","approverType":"ROLE","approverRole":"FINANCE","slaHours":120,"required":true}]'),
('TIMESHEET_WEEKLY',   'Timesheet Weekly Approval',
 'Manager reviews timesheet weekly',                         'TIMESHEET','clock',
 '[{"stepOrder":1,"stepName":"Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":48,"required":true}]'),
('ASSET_REQUEST',      'Asset Request',
 'IT + Manager approval for new asset',                      'ASSET',  'laptop',
 '[{"stepOrder":1,"stepName":"Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":48,"required":true},
   {"stepOrder":2,"stepName":"IT","stepType":"APPROVAL","approverType":"ROLE","approverRole":"IT_ADMIN","slaHours":72,"required":true}]'),
('WFH_REQUEST',        'Work From Home Request',
 'Manager approval for ad-hoc WFH',                          'LEAVE',  'home',
 '[{"stepOrder":1,"stepName":"Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":24,"required":true}]'),
('REGULARIZATION',     'Attendance Regularization',
 'Manager approval to fix missed punches',                   'ATTENDANCE','check',
 '[{"stepOrder":1,"stepName":"Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":48,"required":true}]'),
('COMP_OFF',           'Comp-Off Request',
 'Manager + HR for comp-off',                                'LEAVE',  'clock-rewind',
 '[{"stepOrder":1,"stepName":"Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":48,"required":true},
   {"stepOrder":2,"stepName":"HR","stepType":"APPROVAL","approverType":"HR","slaHours":72,"required":true}]'),
('SEPARATION',         'Resignation - HR + Manager',
 'Two-step exit notification + acceptance',                  'OFFBOARDING','door',
 '[{"stepOrder":1,"stepName":"Manager","stepType":"APPROVAL","approverType":"MANAGER","slaHours":120,"required":true},
   {"stepOrder":2,"stepName":"HR","stepType":"APPROVAL","approverType":"HR","slaHours":120,"required":true}]')
ON CONFLICT (code) DO NOTHING;
